version: '3.4'

services:
  netcoreistio.services.users:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  netcoreistio.services.users-v2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  netcoreistio.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

